### ISSUE TITLE
Unavailable mtx file

### ISSUE THREAD

**Issue by auesro** [ArielLevineLabNINDS/SeqSeek-Classify-NN#2]
Hi @danielruss 
I was trying to download the `filtered_neurons_doublets.mtx` file through git lfs but got the following error:
```
{
  "message": "This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.",
  "documentation_url": "https://docs.github.com/articles/purchasing-additional-storage-and-bandwidth-for-an-organization/"
}
´´´
Could you please fix it or provide the file in some other way?

Thanks a lot!

Cheers,

A

**Comment by danielruss** [comment]
Not an Ideal solution, but you can download the file from:

https://drive.google.com/file/d/1TYA0J8CoaKorycs7_ck28vVSyyNAN9lM/view?usp=sharing

**Warning** It is a 132 MB file GZIPPED file.  The mtx file is 603 MB.
Let me know if you have problems accessing the data.

**Comment by auesro** [comment]
Thanks, @danielruss !
I will get back to you if needed!
